# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Netdata DEV
version: "2.2.8-DEV4"
slug: netdata-dev
description: Netdata - Monitor everything in real time
url: "https://github.com/cryorig/netdata-homeassistant-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
panel_icon: mdi:chart-bell-curve
panel_title: Netdata
ingress: true
ingress_port: 19999
journald: true
apparmor: unconfined
docker_api: true
privileged:
  - SYS_PTRACE
  - SYS_ADMIN
map:
  - config:rw
options:
  hostname: homeassistant
  data_path: /config/netdata
  page_cache_size: 32
  dbengine_disk_space: 256
  enable_alarm: true
  enable_log: true
  claim_url: https://app.netdata.cloud
  claim_token: YOUR_CLAIM_TOKEN
  claim_rooms:
    - REPLACE_WITH_ROOM
schema:
  hostname: str
  page_cache_size: int
  dbengine_disk_space: int
  enable_alarm: bool
  enable_log: bool
  claim_url: str
  claim_token: str
  claim_rooms:
    - str
image: "ghcr.io/cryorig/{arch}-netdata-homeassistant-addon"
